#!/usr/bin/env python3
# Salve como greet.py e torne executável: chmod +x greet.py

nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")

print(f"bom dia! ({nome})")

print (f"você tem {idade} anos")
print (f"em 5 anos você terá {int(idade) + 5} anos")
print (f"em 10 anos você terá {int(idade) + 10} anos")
print (f"em 20 anos você terá {int(idade) + 20} anos")
print (f"em 30 anos você terá {int(idade) + 30} anos")
print (f"em 40 anos você terá {int(idade) + 40} anos")
print (f"em 50 anos você terá {int(idade) + 50} anos")
print (f"em 60 anos você terá {int(idade) + 60} anos")
print (f"em 70 anos você terá {int(idade) + 70} anos")
print (f"em 80 anos você terá {int(idade) + 80} anos")
print (f"em 90 anos você terá {int(idade) + 90} anos")
print (f"em 100 anos você terá {int(idade) + 100} anos")
